# Generated by Django 2.1.8 on 2019-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_no', models.IntegerField()),
                ('chk_iteam', models.CharField(max_length=120)),
                ('chk_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='docinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chk_list', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('comments', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
