# Generated by Django 2.1.8 on 2019-07-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_personinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_master',
            name='chk_type',
            field=models.CharField(max_length=120),
        ),
    ]
