# Generated by Django 2.1.8 on 2019-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_auto_20190712_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
