# Generated by Django 2.1.8 on 2019-07-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_personinfo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist_master',
            old_name='chk_iteam',
            new_name='chk_item',
        ),
    ]
