# Generated by Django 2.1.8 on 2019-07-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20190712_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinfo',
            old_name='car_model',
            new_name='Brand',
        ),
    ]
